# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project_meta\python\inter_camera\view\base_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 523)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Record_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Record_Button.setGeometry(QtCore.QRect(60, 340, 75, 23))
        self.Record_Button.setObjectName("Record_Button")
        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Button.setGeometry(QtCore.QRect(180, 340, 75, 23))
        self.Start_Button.setObjectName("Start_Button")
        self.Stop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_Button.setGeometry(QtCore.QRect(300, 340, 75, 23))
        self.Stop_Button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Stop_Button.setObjectName("Stop_Button")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(390, 340, 201, 121))
        self.listView.setObjectName("listView")
        self.getCameralist_Button = QtWidgets.QPushButton(self.centralwidget)
        self.getCameralist_Button.setGeometry(QtCore.QRect(60, 380, 91, 31))
        self.getCameralist_Button.setObjectName("getCameralist_Button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 50, 381, 211))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Record_Button.setText(_translate("MainWindow", "录制"))
        self.Start_Button.setText(_translate("MainWindow", "开始"))
        self.Stop_Button.setText(_translate("MainWindow", "停止"))
        self.getCameralist_Button.setText(_translate("MainWindow", "获取相机列表"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
